
include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"
    ref: maven-build-script

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"
    ref: maven-build-script
