variables:
  AWS_BUILD_SUBDIR: provider/storage-aws/build-aws
  AWS_TEST_SUBDIR: testing/storage-test-aws
  AWS_SERVICE: storage
  AWS_ENVIRONMENT: dev

  AWS_MONGODB_BUILD_SUBDIR: provider/storage-aws-mongodb/build-aws
  AWS_MONGODB_TEST_SUBDIR: testing/storage-test-aws-mongodb
  AWS_MONGODB_SERVICE: storage
  AWS_MONGODB_ENVIRONMENT: dev
  AWS_MONGODB_SKIP_TESTS: 'true'

  GCP_BUILD_SUBDIR: provider/storage-gcp
  GCP_INT_TEST_SUBDIR: testing/storage-test-gcp
  GCP_APPLICATION_NAME: os-storage
  GCP_ENVIRONMENT: testing
  GCP_PROJECT: opendes-evt
  GCP_TENANT_NAME: opendesevt
  GCP_DEPLOY_ENV: p4d

  OSDU_GCP_ENVIRONMENT: osdu-gcp
  # --- osdu gcp specific variables for cloudrun ---
  OSDU_GCP_SERVICE: storage
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: os-storage
  OSDU_GCP_DEFAULT_DATA_COUNTRY: US
  # --- osdu specific variables for cloudrun storage w/o "/" at the end ---
  OSDU_GCP_ENV_VARS: GOOGLE_AUDIENCES=$GOOGLE_AUDIENCE,AUTHORIZE_API=$OSDU_GCP_AUTHORIZE_API,LEGALTAG_API=$OSDU_GCP_LEGALTAG_API,STORAGE_HOSTNAME=$OSDU_GCP_STORAGE_HOSTNAME,CRS_API=$OSDU_GCP_CRS_API,DEFAULT_DATA_COUNTRY=$OSDU_GCP_DEFAULT_DATA_COUNTRY,REDIS_STORAGE_HOST=$REDIS_STORAGE_HOST,REDIS_GROUP_HOST=$REDIS_GROUP_HOST --vpc-connector=$OSDU_GCP_VPC_CONNECTOR

  AZURE_SERVICE: storage
  AZURE_BUILD_SUBDIR: provider/storage-azure
  AZURE_TEST_SUBDIR: testing/storage-test-azure

  IBM_BUILD_SUBDIR: provider/storage-ibm
  IBM_INT_TEST_SUBDIR: testing/storage-test-ibm

include:
  - project: "osdu/platform/ci-cd-pipelines"
    ref: "release/0.7"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    ref: "release/0.7"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    ref: "release/0.7"
    file: "scanners/fossa.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    ref: "release/0.7"
    file: "cloud-providers/gcp.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    ref: "release/0.7"
    file: "cloud-providers/aws.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    ref: "release/0.7"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    ref: "release/0.7"
    file: "cloud-providers/osdu-gcp-cloudrun.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    ref: "release/0.7"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    ref: "release/0.7"
    file: "cloud-providers/azure.yml"

  - project: 'osdu/platform/ci-cd-pipelines'
    ref: "release/0.7"
    file: 'cloud-providers/aws-mongodb.yml'

# disable the eslint scanner
# I think this is being generated from the presence of an HTML file, but there
# is no javascript to scan, so the job isn't helpful and just gets in the way
eslint-sast:
  rules:
    - when: never
