variables:
  AWS_BUILD_SUBDIR: provider/storage-aws/build-aws
  AWS_TEST_SUBDIR: testing/storage-test-aws
  AWS_SERVICE: storage
  AWS_ENVIRONMENT: dev

  GCP_BUILD_SUBDIR: provider/storage-gcp
  GCP_INT_TEST_SUBDIR: testing/storage-test-gcp
  GCP_APPLICATION_NAME: os-storage
  GCP_ENVIRONMENT: testing
  GCP_PROJECT: opendes-evt
  GCP_TENANT_NAME: opendesevt
  GCP_DEPLOY_ENV: p4d

  AZURE_SERVICE: storage
  AZURE_BUILD_SUBDIR: provider/storage-azure
  AZURE_TEST_SUBDIR: testing/storage-test-azure

  IBM_BUILD_SUBDIR: provider/storage-ibm
  IBM_INT_TEST_SUBDIR: testing/storage-test-ibm

include:
  - project: "osdu/platform/system/storage"
    file: "postman-tests/standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gcp.yml"

  - project: 'osdu/platform/ci-cd-pipelines'
    file: 'cloud-providers/aws.yml'

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

  - project: "osdu/platform/system/storage"
    file: "postman-tests/postman.yml"

# disable the eslint scanner
# I think this is being generated from the presence of an HTML file, but there
# is no javascript to scan, so the job isn't helpful and just gets in the way
eslint-sast:
  rules:
    - when: never
