variables:
  AWS_BUILD_SUBDIR: provider/storage-aws/build-aws
  AWS_TEST_SUBDIR: testing/storage-test-aws
  AWS_SERVICE: storage
  AWS_ENVIRONMENT: dev

  GCP_BUILD_SUBDIR: provider/storage-gcp
  GCP_INT_TEST_SUBDIR: testing/storage-test-gcp
  GCP_APPLICATION_NAME: os-storage
  GCP_ENVIRONMENT: testing
  GCP_PROJECT: opendes-evt
  GCP_TENANT_NAME: opendesevt
  GCP_DEPLOY_ENV: p4d

  OSDU_GCP_BUILD_SUBDIR: provider/storage-gcp
  OSDU_GCP_INT_TEST_SUBDIR: testing/storage-test-gcp
  OSDU_GCP_APPLICATION_NAME: os-storage
  OSDU_GCP_ENVIRONMENT: osdu-gcp
  OSDU_GCP_PROJECT: nice-etching-277309
  OSDU_GCP_TENANT_NAME: osdu
  OSDU_GCP_DEPLOY_ENV: empty

  # --- osdu gcp specific variables for cloudrun ---
  OSDU_GCP_SERVICE: storage
  OSDU_GCP_VENDOR: gcp
  OSDU_GCP_APPLICATION_NAME: os-storage
  OSDU_GCP_ENV_VARS: GCP_ENTITLEMENTS_URL=$OSDU_GCP_ENTITLEMENTS_URL,GCP_SEARCH_QUERY_URL=$OSDU_GCP_SEARCH_QUERY_URL,GCP_REDIS_HOST=$REDIS_GROUP_HOST --vpc-connector=$OSDU_GCP_VPC_CONNECTOR
#   --set-env-vars=SPRING_PROFILES_ACTIVE=${ENVIRONMENT},GOOGLE_AUDIENCES=${GOOGLE_AUDIENCES},STORAGE_HOSTNAME=${STORAGE_HOSTNAME_CLOUDRUN},REDIS_GROUP_HOST=${REDIS_GROUP_HOST},REDIS_STORAGE_HOST=${REDIS_STORAGE_HOST},AUTHORIZE_API=${AUTHORIZE_API},LEGALTAG_API=${LEGALTAG_API},CRS_API=${CRS_API}
      


  AZURE_SERVICE: storage
  AZURE_BUILD_SUBDIR: provider/storage-azure
  AZURE_TEST_SUBDIR: testing/storage-test-azure

  IBM_BUILD_SUBDIR: provider/storage-ibm
  IBM_INT_TEST_SUBDIR: testing/storage-test-ibm

include:
  - project: "osdu/platform/ci-cd-pipelines"
    file: "standard-setup.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "build/maven.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/fossa.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/gcp.yml"

  - project: 'osdu/platform/ci-cd-pipelines'
    file: 'cloud-providers/aws.yml'

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/ibm.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/osdu-gcp.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "scanners/gitlab-ultimate.yml"

  - project: "osdu/platform/ci-cd-pipelines"
    file: "cloud-providers/azure.yml"

# disable the eslint scanner
# I think this is being generated from the presence of an HTML file, but there
# is no javascript to scan, so the job isn't helpful and just gets in the way
eslint-sast:
  rules:
    - when: never