AZURE_TENANT_ID: "58975fd3-4977-44d0-bea8-37af0baac100"
AZURE_CLIENT_ID: "a38fdd7b-f209-4552-96cd-126ec2494605"
AZURE_CLIENT_SECRET: "AI2hECiLwXj~B_1Pt-XyQojRxkwvMmB3b8"
KEYVAULT_URI: "https://osdu-mvp-crdev-vq1b-kv.vault.azure.net/"
aad_client_id: "8fec8527-6e09-4978-9786-1ad15a92d8a7"
appinsights_key: "a1e199f2-2352-4508-83b5-773526946f03"
cosmosdb_account: "https://osdu-mvp-dp1dev-qs29-db.documents.azure.com:443/"
cosmosdb_database: "osdu-db"
cosmosdb_key: "prCbETvXMkN3VEUxmDJqa9ubkNF7SDDsckAD4CgZyQcqVrEiKu6rGUbmLeFexeUPEAWZwmFQsxj6W4DMzUIXVg=="
entitlements_app_key: "OBSOLETE"
entitlements_service_api_key: "OBSOLETE"
#entitlements_service_endpoint: "https://osdu-dev.msft-osdu-test.org/entitlements/v1"
entitlements_service_endpoint: "http://localhost:8080/api/entitlements/v2"
legal_service_endpoint: "https://osdu-dev.msft-osdu-test.org/api/legal/v1"
legal_service_region: "centralus"
search_service_endpoint: "https://osdu-dev.msft-osdu-test.org/api/search/v2/query"
servicebus_namespace_name: "osdu-mvp-dp1dev-qs29-bus"
servicebus_connection_string: "Endpoint=sb://osdu-mvp-dp1dev-qs29-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=CZ9qJpCIpK7OBleCeiJsmdPoLxkqj5iZNWDY/bUukbc="
servicebus_topic_name: "recordstopic"
storage_account: "osdumvpdp1devqs29data"
storage_account_key: "XzFc/J0JNJKondCBYRFyxMMVwM+azygaMcDOoYb94NSdMj1ip0s77ebkdoivRN8DTeulCtoQL/03ddNaP8Kcug=="
partition_service_endpoint: "https://osdu-dev.msft-osdu-test.org/api/partition/v1/"
azure_istioauth_enabled: "true"
server_port: "8082"
REDIS_DATABASE: "5"
policy_enabled: "false"
SPRING_CONFIG_NAME: "common,application"
policy_service_endpoint: ""
legal_servicebus_topic_name: "x"