{{- if .Values.envoyFilter.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: {{ .Release.Name }}-ratelimit
  namespace: osdu
spec:
  workloadSelector:
    labels:
      app: {{ .Release.Name }}
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: SIDECAR_INBOUND   # will match outbound listeners in all sidecars
      listener:
        filterChain:
          filter:
            name: envoy.http_connection_manager
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
              token_bucket:
                max_tokens: {{ .Values.envoyFilter.rateLimit.max_tokens }}    #The maximum tokens that the bucket can hold. 
                tokens_per_fill: {{ .Values.envoyFilter.rateLimit.tokens_per_fill }}  #The number of tokens added to the bucket during each fill interval.    
                fill_interval: {{ .Values.envoyFilter.rateLimit.fill_interval }}   #The fill interval that tokens are added to the bucket in seconds.
              filter_enabled:
                runtime_key: local_rate_limit_enabled
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              filter_enforced:
                runtime_key: local_rate_limit_enforced
                default_value:
                  numerator: 100
                  denominator: HUNDRED
              response_headers_to_add:
                - append: true
                  header:
                    key: x-local-rate-limit
                    value: 'true'
{{- end }}