apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ .Values.conf.app_name }}
  name: {{ .Values.conf.configmap }}
  namespace: {{ .Release.Namespace }}
data:
  AUTHORIZE_API: "http://{{ .Values.conf.ent_name }}.{{ .Release.Namespace }}{{ .Values.data.authorize_api }}"
  LOG_LEVEL: "{{ .Values.data.log_level }}"
  LEGALTAG_API: "http://{{ .Values.conf.legal_name }}.{{ .Release.Namespace }}{{ .Values.data.authorize_api }}"
  GOOGLE_AUDIENCES: "{{ .Values.data.google_audiences }}"
  STORAGE_HOSTNAME: "{{ .Values.conf.app_name }}"
  REDIS_GROUP_HOST: "{{ .Values.data.redis_group_host }}"
  REDIS_STORAGE_HOST: "{{ .Values.data.redis_storage_host }}"
  CRS_API: "{{ .Values.data.crs_api }}"
  DEFAULT_DATA_COUNTRY: "{{ .Values.data.default_data_country }}"
---

