version: "3"
services:
  os-storage-app:
    build:
      args: 
        JAR_FILE: target/storage-reference-0.0.5-SNAPSHOT-spring-boot.jar
      context: ""
      dockerfile: ../Dockerfile
    image: us.gcr.io/osdu-anthos-02/os-storage/anthos-storage-reference
    ports:
     - "8080:8080"

